### ISSUE TITLE
Fix HTML console warnings for faculty and room components

### ISSUE THREAD

**Issue by timothyro** [room-directory/room-directory#208]
- [x] Faculty and Room table components generate a warning "react_devtools_backend.js:2655 Warning: Each child in a list should have a unique "key" prop." (Faculty.jsx, FacultyInfo.jsx, RoomTable.jsx, FacultyTable.jsx)
- [x] Room List page generates "Error: <path> attribute d: Expected number, "….13623,-0.10254 v -8.05078 -8.05…"." and "Warning: validateDOMNesting(...): \<div> cannot appear as a child of <tbody>." (RoomList.jsx)

Please do work for this task in a branch called issue-208.

**Comment by KyoufuuN1K1** [comment]
Unable to resolve <key> issue for Faculty Info page and the attribute error on the room list page
