### ISSUE TITLE
Review files in the api folder

### ISSUE THREAD

**Issue by khirano7** [room-directory/room-directory#216]
Make sure comments are related and delete unused code

- [x]  base, club, faculty, matp, request ( Tim, issue-216-a ) *request getting deleted*
- [x]  reservation, role, room, utilities ( Cam issue-216-b )
- [x]  user (Trey, issue-216-c )

Please do work for this task in a branch called issue-216.

**Comment by yertsti** [comment]
Trey: 216-c
