### ISSUE TITLE
Review files in the ui/pages folder

### ISSUE THREAD

**Issue by khirano7** [room-directory/room-directory#218]
Make sure comments are related and delete unused code

- [x]  (AddReservation.jsx to EditStuff.jsx) -> AddManage.jsx to EditProfile.jsx ( Jeraldine, issue-218-a )
- [x]  FacultyInfo.jsx to NotFound.jsx ( Jeraldine, issue-218-b )
- [x]  Profile.jsx to StudentRequests.jsx ( Cameron, issue-218-c )

Please do work for this task in a branch called issue-218.

**Comment by itsjerie** [comment]
There's still a  TO DO in AddManage.jsx

**Comment by KyoufuuN1K1** [comment]
No unrelated comments or unused code found in FacultyInfo.jsx to NotFound.jsx. No changes to these files will be made on my end.
