### ISSUE TITLE
Review: FacultyInfo.jsx and Profile.jsx

### ISSUE THREAD

**Issue by khirano7** [room-directory/room-directory#54]
## Overview
- We are going to conduct our first IDPM Review.

## Review Branch
- [review-1](https://github.com/room-directory/room-directory/tree/review-1)

## Files to review
- [FacultyInfo.jsx](https://github.com/room-directory/room-directory/blob/review-1/app/imports/ui/pages/FacultyInfo.jsx)
- [Profile.jsx](https://github.com/room-directory/room-directory/blob/review-1/app/imports/ui/pages/Profile.jsx)

## Checklists
- [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
- [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
- [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
- [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

## Due date
1/30

## For more information
The review process is documented at: http://courses.ics.hawaii.edu/ics414s23/morea/review/reading-idpm-review.html

**Comment by khirano7** [comment]
## FacultyInfo.jsx
- Design-05: maybe add future features in a "TODO" comment
- Design-07: Add comments describing what the code does
- L54: may want to change "Loading Stuff" to "Loading Faculty Info" or something similar

## Profile.jsx
- Design-05: Update the TODO comment
- Design-07: Add comments describing what the code does
- Possibly move modal to a new component?

**Comment by KyoufuuN1K1** [comment]
FacultyInfo.jsx
DE-05: Needs more comments to explain the code.
DE-07: Code is not intuitively readable. A header comment per section would help.

Profile.jsx
DE-07: Needs comments to understand code

**Comment by yertsti** [comment]
### FacultyInfo.jsx
Design-03 In the future it will be used, but line  54 is never used cause the conditional is if(true) 
JS-08 Add jsdoc comments to component
### Profile.jsx
JS-08 add jsdoc comments
REACT-01 Modal could be component

**Comment by carakaki808** [comment]
### FacultyInfo.jsx

L29…36: React-01: Move to components?
UI-02: Not enough screen real estate for mobile
### Profile.jsx

UI-02: Not enough screen real estate for mobile

**Comment by timothyro** [comment]
# FacultyInfo.jsx
- DESIGN-05: TODO make profiles into a component

# Profile.jsx
- REACT-01: Modal as component

**Comment by jing2003** [comment]
**FacultyInfo.jsx**

- Design-07: add comments to better understand the code

**Profile.jsx**

- Design-07: add comments to better understand the code

**Comment by michnotmeesh** [comment]
FacultyInfo.jsx

- Design-02: No nested conditions...but `ready` variable is always true. Will be used once collections are connected to this page.

Profile.jsx

- React-01: Reservations modal could be a modal

**Comment by sumidaca** [comment]
FacultyInfo.jsx
Design-05: Add TODO comment to note future features and improvements
Design-07: Add comments explaining code


Profile.jsx
Design-07: Add comments explaining code

**Comment by itsjerie** [comment]
FacultyInfo.jsx
D-07: Add comments explaining your code
Profile.jsx
D-07: Add comments explaining your code

**Comment by timothyro** [comment]
# Outcome of Review Meeting
New checklist items:
- DESIGN-05: TODO comments
