### ISSUE TITLE
Review: FacultyRequests.jsx and ReservationCollection.js

### ISSUE THREAD

**Issue by khirano7** [room-directory/room-directory#87]
## Overview
We are going to conduct our second IDPM Review.

## Review Branch
[review-2](https://github.com/room-directory/room-directory/tree/review-2)

## Files to review
[FacultyRequests.jsx](https://github.com/room-directory/room-directory/blob/review-2/app/imports/ui/pages/FacultyRequests.jsx)
[ReservationCollection.js](https://github.com/room-directory/room-directory/blob/review-2/app/imports/api/reservation/ReservationCollection.js)

## Checklists
[Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
[Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
[JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
[React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)

## Due date

2/6

## For more information
The review process is documented at: http://courses.ics.hawaii.edu/ics414s23/morea/review/reading-idpm-review.html

**Comment by timothyro** [comment]
## FacultyRequests.jsx
- Design-05: TODO make table rows into component that pulls from collection

## ReservationCollection.js
- Design-05: is docID the MongoDB generated random characters?

**Comment by michnotmeesh** [comment]
ReservationCollection.js

- METEOR-04: Use validated methods to update collections. Need to research what this means.

FacultyRequests.js

- REACT-01: Need to implement component to populate requests

**Comment by itsjerie** [comment]
### FacultyRequests.jsx

- D-05: L5 fix comment 

### ReservationCollection.js

- D-04: L26-36 , L50-60, L87-91, L99-102, L126-128, L36-139, L147-152, L157-161, L175-177 Make comments one line if possible

**Comment by khirano7** [comment]
## FacultyRequests.jsx
- Design-05: Add a TODO Comment for future features
- Design-05: L5 comment related to Stuff
- React-01: when implementing collection data, table entries should be a component

## ReservationCollection.js
- JS-08: look at L107 and L116
- Is it possible to make the update() function more compact?

**Comment by sumidaca** [comment]
FacultyRequests.jsx

- L27-50: Design-01/React-01: Lines are dulicated, could be made a component
- L5: Design-05: Remove comment referencing stuff

ReservationRequests.js

- L178: React-08: Export is named Reservations rather than ReservationCollection

**Comment by yertsti** [comment]
### FacultyRequest.jsx
- JS-08: Stuff is referenced. Replace with faculty request.
### ReservationRequest.js
- JS-08: Stuff is referenced. Replace with Reservation request.

**Comment by jing2003** [comment]
FacultyRequests.jsx

- L5: remove comments about stuff

ReservationCollection.js

- L178: naming

**Comment by KyoufuuN1K1** [comment]
FacultyRequests.jsx
DE-05:
	Line 5: Comment still uses Stuff.

ReservationRequests.js
RE-08:
	Line 178: export naming needs to be consistent

**Comment by khirano7** [comment]
## Outcome of Review Meeting
New checklist item:
- refer to TODO comments added in review-2 branch

**Comment by carakaki808** [comment]
FacultyRequests.jsx
- DE-05: Line-5: Remove stuff from comment

ReservationRequests.js
- DE-04: Cut down on large comment blocks
